import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  // --- UPDATED: Explicitly load required weights, including '900' for maximum boldness ---
  weight: ['400', '500', '700', '900'], 
  // 400: Regular, 500: Medium, 700: Bold, 900: ExtraBold/Black
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  // --- Explicitly load required weights ---
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "EduSpot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
